//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excavator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#933D00&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#425B60&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;50.8381,1.7059,-2.56 50.4313,1.8524,-2.56 50.6428,1.8014,-2.56 53.487,1.6301,-2.56 50.8092,1.6601,-2.5384 47.4752,2.231,-2.56 50.4244,1.7986,-2.5384 51.0978,1.541 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arm {
            get {
                return ResourceManager.GetString("Arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#9EAD70&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#FFFFFF&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-1.8589,0,-0.24486 1.8589,0,-0.24486 1.875,0,2.2961E-16 1.875,25,2.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArmCyl {
            get {
                return ResourceManager.GetString("ArmCyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#00FF00&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#F40000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#0000FF&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-0.98769,0,-0.15641 0.98769,0,-0.15641 1,0,1.2246E-16 1,26,1.2246E-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArmPiston {
            get {
                return ResourceManager.GetString("ArmPiston", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#0000FF&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#9E0000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;101.6396,2.4821,-4.345 101.108,1.9674,-4.345 101.3003,1.3756,-4.345  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Boom {
            get {
                return ResourceManager.GetString("Boom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#FF0000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#050000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#00FFFF&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-2.1052,0,-0.28946 2.1052,0,-0.28946 2.125,0,2.6023E-16 2.125,26,2.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoomCyl {
            get {
                return ResourceManager.GetString("BoomCyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#00FF00&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#00FF00&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#FF0000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-0.98637,0,-0.16455 0.98637,0,-0.16455 1,0,1.2246E-16 1,26.72,1.2246 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoomPiston {
            get {
                return ResourceManager.GetString("BoomPiston", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Viewport3D xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Viewport3D.Camera&gt;
        ///        &lt;OrthographicCamera Position=&quot;1.297541,1.525930,1.297541&quot; LookDirection=&quot;-0.577382,-0.577288,-0.577382&quot; UpDirection=&quot;-0.408204,0.816541,-0.408204&quot; NearPlaneDistance=&quot;1.123643&quot; FarPlaneDistance=&quot;3.370928&quot; Width=&quot;2.247286&quot;/&gt;
        ///    &lt;/Viewport3D.Camera&gt;
        ///    &lt;Viewport3D.Children&gt;
        ///        &lt;ModelVisual3D&gt;
        ///            &lt;ModelV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#7D7D7D&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#FFFFFF&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-11.91,-8.66,9.3301 -12.62,-8.66,10.7749 0,-8.66,10.2365 -1.6367E-15 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bucket {
            get {
                return ResourceManager.GetString("Bucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#0000F9&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#4C0000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#00FF00&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-1.7305,0,-0.26082 1.7305,0,-0.26082 1.75,0,2.1431E-16 1.75,20,2.143 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BucketCyl {
            get {
                return ResourceManager.GetString("BucketCyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#00FF00&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;0,0.65076,-1.3514 0,0.44248,-0.7664 0,-1.0838E-16,-0.885 -6.27,-1.08 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BucketLink {
            get {
                return ResourceManager.GetString("BucketLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#FFFF00&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-0.58549,0.93751,3.0435 -0.58496,0.93784,2.9648 -1.1053,0,2.9648 -1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BucketLink2 {
            get {
                return ResourceManager.GetString("BucketLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#0000FF&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-0.86171,0,-0.1519 0.86171,0,-0.1519 0.875,0,1.0715E-16 0.875,20.63, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BucketPiston {
            get {
                return ResourceManager.GetString("BucketPiston", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#7D7C7D&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#FFFFFF&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;9.160244,-1.018506,12 9.160244,-1.018506,-12 8.172136,7.449502,12 8. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BucketSimple {
            get {
                return ResourceManager.GetString("BucketSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt1 {
            get {
                object obj = ResourceManager.GetObject("dirt1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt2 {
            get {
                object obj = ResourceManager.GetObject("dirt2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt3 {
            get {
                object obj = ResourceManager.GetObject("dirt3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt4 {
            get {
                object obj = ResourceManager.GetObject("dirt4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt5 {
            get {
                object obj = ResourceManager.GetObject("dirt5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#191919&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#070707&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;10.67486,-10.57443,4.330081 -10.9165,-10.57443,-3.68997 -11.27632,-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dull_Butt {
            get {
                return ResourceManager.GetString("Dull_Butt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#CAD1EE&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-11.95892,0.716341,-23.14627 -11.94825,0.7264908,-23.1498 -11.96873, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dull_Cab {
            get {
                return ResourceManager.GetString("Dull_Cab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream excavator_idle {
            get {
                return ResourceManager.GetStream("excavator_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#FF0000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;-0.28439,-0.33333,-5.48 -0.76159,-0.38868,-5.48 -0.85238,-0.067537,- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varying vec2 texCoords;
        ///uniform sampler2D tex0;
        ///uniform sampler2D tex1;
        ///
        ///void main()
        ///{	
        ///	gl_FragColor = texture2D(tex0, texCoords);
        ///	gl_FragColor.a = 0.4f;
        ///	gl_FragDepth = texture2D(tex1, texCoords);
        ///}
        ///.
        /// </summary>
        internal static string GhostFragment {
            get {
                return ResourceManager.GetString("GhostFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varying vec2 texCoords;
        ///void main()
        ///{
        ///	gl_Position = ftransform();
        ///	texCoords = gl_MultiTexCoord0.st;
        ///}
        ///.
        /// </summary>
        internal static string GhostVertex {
            get {
                return ResourceManager.GetString("GhostVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass1 {
            get {
                object obj = ResourceManager.GetObject("grass1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass2 {
            get {
                object obj = ResourceManager.GetObject("grass2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green {
            get {
                object obj = ResourceManager.GetObject("green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HeightMap {
            get {
                object obj = ResourceManager.GetObject("HeightMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varying vec4 vertex_shadow;
        ///uniform sampler2D ShadowMap; // Shadow
        ///
        ///varying vec4 ambColor;
        ///varying vec4 difColor;
        ///varying float shadow_intensity;
        ///
        ///void main()
        ///{		
        ///	vec4 shadowCoordinateWdivide = vertex_shadow / vertex_shadow.w ;
        ///
        ///	bool b1 = shadowCoordinateWdivide.x &gt; 0 &amp;&amp; shadowCoordinateWdivide.x &lt; 1;
        ///	bool b2 = shadowCoordinateWdivide.y &gt; 0 &amp;&amp; shadowCoordinateWdivide.y &lt; 1;
        ///
        ///	if (b1 &amp;&amp; b2)
        ///	{
        ///		shadowCoordinateWdivide.z -= 0.0001;
        ///
        ///		float distanceFromLight = texture(ShadowMap, shadowCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShadowFragment {
            get {
                return ResourceManager.GetString("ShadowFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Used for shadow lookup
        ///varying vec4 vertex_shadow;
        ///varying vec3 vertex_light_position;
        ///varying vec3 vertex_normal;
        ///
        ///
        ///varying vec4 ambColor;
        ///varying vec4 difColor;
        ///varying float shadow_intensity;
        ///
        ///void main()
        ///{
        ///	ambColor = gl_FrontMaterial.ambient * (gl_LightSource[0].ambient +  gl_LightModel.ambient);
        ///    difColor = gl_FrontMaterial.diffuse * gl_LightSource[0].diffuse;
        ///
        ///	gl_Position = gl_ProjectionMatrix * gl_ModelViewMatrix * gl_Vertex;
        ///	vertex_shadow = gl_TextureMatrix[7] * gl_Vertex;   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShadowVertex {
            get {
                return ResourceManager.GetString("ShadowVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varying vec4 vertex_shadow;
        ///varying vec2 texCoords;
        ///
        ///varying vec4 ambColor;
        ///varying vec4 difColor;
        ///varying float shadow_intensity;
        ///
        ///uniform sampler2D ShadowMap; // Shadow
        ///uniform sampler2D tex0; // Soil
        ///
        ///void main()
        ///{		
        ///	vec4 shadowCoordinateWdivide = vertex_shadow / vertex_shadow.w ;
        ///
        ///	bool b1 = shadowCoordinateWdivide.x &gt; 0 &amp;&amp; shadowCoordinateWdivide.x &lt; 1;
        ///	bool b2 = shadowCoordinateWdivide.y &gt; 0 &amp;&amp; shadowCoordinateWdivide.y &lt; 1;
        ///
        ///	if (b1 &amp;&amp; b2)
        ///	{
        ///		shadowCoordinateWdivide.z -= 0.0001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoilFragment {
            get {
                return ResourceManager.GetString("SoilFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Used for shadow lookup
        ///varying vec4 vertex_shadow;
        ///varying vec3 vertex_light_position;
        ///varying vec3 vertex_normal;
        ///varying vec2 texCoords;
        ///
        ///varying vec4 ambColor;
        ///varying vec4 difColor;
        ///varying float shadow_intensity;
        ///
        ///void main()
        ///{
        ///	ambColor = gl_FrontMaterial.ambient * (gl_LightSource[0].ambient +  gl_LightModel.ambient);
        ///    difColor = gl_FrontMaterial.diffuse * gl_LightSource[0].diffuse;
        ///
        ///	gl_Position = gl_ProjectionMatrix * gl_ModelViewMatrix * gl_Vertex;
        ///	vertex_shadow = gl_TextureM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoilVertex {
            get {
                return ResourceManager.GetString("SoilVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#FFFFFF&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;1.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;32.0827,-1.308,2.9176 31.57,-1.153,1.68 31.57,-1.308,1.68 32.0827,-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SwingFrame {
            get {
                return ResourceManager.GetString("SwingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#CC6022&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#331808&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;3.91302,15.1825,0.712412 4.20503,15.5998,0.598042 4.65173,16.929,7.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tree1 {
            get {
                return ResourceManager.GetString("tree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#CCCCCC&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#333333&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;0.0955197,4.4464,0.10098 0.0873382,4.46154,0.0767007 0.118151,4.5154 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tree2 {
            get {
                return ResourceManager.GetString("tree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#CCA18C&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#332823&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;0.463217,1.7272,-0.00370705 0.528827,0,-0.00936937 0.372022,0,-0.376 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tree3 {
            get {
                return ResourceManager.GetString("tree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#CCA371&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#33281C&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;0.841111,2.159,-0.0137955 0.847707,0,-0.0014205 0.607402,0,-0.604144 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tree4 {
            get {
                return ResourceManager.GetString("tree4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#CC9987&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#332621&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;0.50798,1.8288,-0.4073 0.572335,-1.23198E-05,-0.391045 0.557033,-1.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tree5 {
            get {
                return ResourceManager.GetString("tree5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModelVisual3D.Children&gt;
        ///&lt;GeometryModel3D&gt;
        ///&lt;DiffuseMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#CC704F&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/DiffuseMaterial&gt;
        ///&lt;SpecularMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/SpecularMaterial&gt;
        ///&lt;AmbientMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#331C13&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/AmbientMaterial&gt;
        ///&lt;EmissionMaterial&gt;
        ///&lt;SolidColorBrush Color=&quot;#000000&quot; Opacity=&quot;0.0000&quot;/&gt;
        ///&lt;/EmissionMaterial&gt;
        ///&lt;MeshGeometry3D Positions=&quot;0.344393,1.59687,0.196333 0.407931,0.199864,0.203413 0.281588,0.1998 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tree6 {
            get {
                return ResourceManager.GetString("tree6", resourceCulture);
            }
        }
    }
}
